# Generated by Django 4.1 on 2022-12-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='profile_name',
            new_name='profilename',
        ),
    ]
