# Generated by Django 4.1 on 2022-12-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_rename_profile_name_work_profilename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='ExperienceWork',
        ),
    ]
