# Generated by Django 4.1 on 2022-12-27 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0008_certificate_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogPage',
        ),
    ]
