# Generated by Django 4.1 on 2022-12-27 11:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_rename_blog_blogpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('Description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
