# Generated by Django 4.1 on 2022-12-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_remove_certificate_date_remove_certificate_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/certificates'),
        ),
    ]
