# Generated by Django 4.1 on 2022-12-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_rename_body_blogpage_content_remove_blogpage_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
