# Generated by Django 4.1 on 2022-12-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_alter_blogpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/Blogimage'),
        ),
    ]
