# Generated by Django 4.1 on 2022-12-28 13:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_alter_blogpage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatar/achievement')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
