# Generated by Django 4.1 on 2022-12-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0020_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
    ]
